const ts=require('typescript');const fs=require('fs');const assert=require('node:assert/strict');
require.extensions['.ts']=(m,p)=>m._compile(ts.transpileModule(fs.readFileSync(p,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,p);
const {newProperty,validateState}=require('../lib/model.ts');const {reviewRows,applyReview,applyOneReview,removeReviewRow}=require('../lib/batch-review.ts');
const hash='a'.repeat(64);const prop=(name)=>({...newProperty(),name,images:[hash],suggestedPrice:'155'});
const base=()=>({properties:[],drafts:[{id:'d1',image:hash,text:'test',properties:[prop('甲小区'),prop('乙小区'),prop('丙小区')]}]});
(async()=>{
 const defaultRows=reviewRows(base());assert(defaultRows.every(r=>/^\d{4}-\d{2}-\d{2}$/.test(r.date)),'缺失报价日期默认当天');
 let state=base();let rows=reviewRows(state);assert(rows.every(r=>!r.checked),'不得默认确认');rows[0].checked=rows[1].checked=true;rows[0].date='2026-09-08';rows[2].property.name='丙小区修改';rows[2].date='2026-09-07';rows[2].quoteNote='留作草稿';let next=await applyReview(state,rows,true,async()=>true);assert.equal(next.properties.length,2);assert.equal(next.drafts[0].properties.length,1);assert.equal(next.drafts[0].properties[0].name,'丙小区修改');assert.equal(next.drafts[0].properties[0].suggestedDate,'2026-09-07');assert.equal(next.properties[0].quotes[0].amount,155);assert.equal(state.properties.length,0);assert(validateState(next));
 rows=reviewRows(base());rows[0].checked=rows[1].checked=true;rows[1].amount='-1';await assert.rejects(applyReview(base(),rows,true,async()=>true),/第2行/);rows[1].amount='155';rows[1].date='2026-02-31';await assert.rejects(applyReview(base(),rows,true,async()=>true),/日期无效/);
 state=base();rows=reviewRows(state);rows.forEach(r=>r.checked=true);next=await applyReview(state,rows,true,async()=>true);assert.equal(next.properties.length,3);assert.equal(next.drafts.length,0);
 state=base();const old={...prop('甲小区'),id:'existing',floor:'中楼层',quotes:[{id:'q0',amount:160,date:'2026-08-01',createdAt:'2026-08-01T00:00:00Z',note:''}]};state.properties.push(old);rows=reviewRows(state);rows[0].target=old.id;rows[0].property.floor='高楼层';rows[0].checked=true;next=await applyReview(state,rows,true,async()=>false);assert.equal(next.properties.length,1);assert.equal(next.properties[0].floor,'中楼层');assert.deepEqual(next.properties[0].quotes[0],old.quotes[0]);assert.equal(next.properties[0].quotes.length,2);assert.equal(next.properties[0].images.length,1);
 rows=reviewRows(state);rows[0].amount='170';rows[0].date='2026-09-08';rows[0].target=old.id;next=await applyReview(state,rows,false,async()=>true);const again=reviewRows(next);assert.equal(again[0].amount,'170');assert.equal(again[0].date,'2026-09-08');assert.equal(again[0].target,old.id);assert.equal(next.properties.length,1);
 state=base();rows=reviewRows(state);rows[1].property.area='53.2';rows[1].amount='185';next=await applyOneReview(state,rows,1,async()=>true);assert.equal(next.properties.length,1);assert.equal(next.properties[0].name,'乙小区');assert.equal(next.properties[0].area,'53.2');assert.equal(next.properties[0].quotes[0].amount,185);assert.equal(next.drafts[0].properties.length,2);assert.equal(next.drafts[0].properties[0].name,'甲小区');
 state=base();rows=reviewRows(state);next=removeReviewRow(state,rows[1]);assert.equal(next.properties.length,0);assert.deepEqual(next.drafts[0].properties.map(p=>p.name),['甲小区','丙小区']);
 console.log('PASS: default unchecked; multi-row commit; unselected edits preserved; invalid batch rejected; all rows committed; merge preserves history and conflict values; draft amounts/dates/targets survive reopening.');
})().catch(e=>{console.error(e);process.exitCode=1});
